### ISSUE TITLE
Support for Containers

### ISSUE THREAD

**Issue by hvandenb** [manoelcampos/cloudsim-plus-automation#3]
Do you already have support for Containers?

**Comment by manoelcampos** [comment]
Unfortunately, the current version is just compatible with CloudSim 3. There is no planning to include the Container support introduced in CloudSim 4. In fact, the Container implementation was made by just copying and pasting lots of existing classes, completely duplicating a huge amount of code. That was the main reason for us to start [CloudSim Plus](http://cloudsimplus.org).

Anyway, we are open for contributions.
